services:
  backend1: &backend1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
      - "35729:35729"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/transactions_control"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
      SPRING_JACKSON_PROPERTY_NAMING_STRATEGY: SNAKE_CASE
      SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE: UTC
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  backend2:
    <<: *backend1
    container_name: backend2
    ports:
      - "8082:8080"

  load-balancer:
    container_name: load-balancer
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "transactions_control"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d transactions_control" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
volumes:
  pgdata:

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1